VP-7240: Add StoreNotificationSenderUnitTests
VirtoCommerce/vc-module-store pull request #70
Opened 2021-03-05 11:39 UTC by eMazeika

Cover StoreNotificationSender scenarios https://virtocommerce.atlassian.net/browse/VP-6892

2021-03-05 12:00 UTC, Vectorfield4 requested changes
Please, add a link to the current Jira task (VP-7240).

2021-03-05 12:00 UTC, Vectorfield4 commented on tests/VirtoCommerce.StoreModule.Tests/StoreNotificationSenderUnitTests.cs
> +        public StoreNotificationSenderUnitTests()
The constructor is redundant.

2021-03-05 12:00 UTC, Vectorfield4 commented on tests/VirtoCommerce.StoreModule.Tests/StoreNotificationSenderUnitTests.cs
> +            _mockStoreService.Setup(ss => ss.GetByIdAsync(It.IsAny<string>(), It.IsAny<string>())).Returns(Task.FromResult(GetStore()));
Can we use everywhere the `.ReturnAsync` method?

2021-03-05 12:00 UTC, Vectorfield4 commented on tests/VirtoCommerce.StoreModule.Tests/StoreNotificationSenderUnitTests.cs
> +        internal static CustomUserManager GetTestUserManager(Mock<IUserStore<ApplicationUser>> storeMock = null)
Please, add a comment above this line:
``` csharp
// TODO: PT-274 Move mock of AspNetUserManager to the platform
```

2021-03-05 12:00 UTC, Vectorfield4 commented on tests/VirtoCommerce.StoreModule.Tests/StoreNotificationSenderUnitTests.cs
> +    internal class CustomUserManager : AspNetUserManager<ApplicationUser>
Please, add a comment above this line:
``` csharp
// TODO: PT-274 Move mock of AspNetUserManager to the platform
```

2021-03-05 13:08 UTC, eMazeika commented on tests/VirtoCommerce.StoreModule.Tests/StoreNotificationSenderUnitTests.cs
> +        public StoreNotificationSenderUnitTests()
ok

2021-03-09 07:53 UTC, Vectorfield4 approved these changes

2021-03-09 07:54 UTC, merged