PT-227: Change the catalog selector on a store blade to an universal platform drop-down
VirtoCommerce/vc-module-store pull request #72
Opened 2021-03-16 16:18 UTC by akak1977

https://virtocommerce.atlassian.net/browse/PT-227

2021-03-16 16:42 UTC, Vectorfield4 requested changes

2021-03-16 16:42 UTC, Vectorfield4 commented on src/VirtoCommerce.StoreModule.Web/Scripts/blades/store-detail.tpl.html
> +                        <ui-scroll-drop-down
Need to check this test case https://virtocommerce.atlassian.net/browse/VP-7260 manualy before merging in dev.

2021-03-17 06:41 UTC, eMazeika requested changes
Ensure that ui-scroll-store is not used anywhere and remove the component

2021-03-17 08:19 UTC, akak1977 commented
So trivial. Should be done later.

2021-03-17 08:19 UTC, closed without merging